[2025-02-05T07:24:51.512+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T07:24:51.543+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_bash_dag_okok.dbt_debug manual__2025-02-05T07:24:48.222280+00:00 [queued]>
[2025-02-05T07:24:51.558+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_bash_dag_okok.dbt_debug manual__2025-02-05T07:24:48.222280+00:00 [queued]>
[2025-02-05T07:24:51.560+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T07:24:51.589+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-02-05 07:24:48.222280+00:00
[2025-02-05T07:24:51.601+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=668) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T07:24:51.605+0000] {standard_task_runner.py:64} INFO - Started process 669 to run task
[2025-02-05T07:24:51.603+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_bash_dag_okok', 'dbt_debug', 'manual__2025-02-05T07:24:48.222280+00:00', '--job-id', '45', '--raw', '--subdir', 'DAGS_FOLDER/test_dbt_2.py', '--cfg-path', '/tmp/tmpuhl2bkyz']
[2025-02-05T07:24:51.606+0000] {standard_task_runner.py:91} INFO - Job 45: Subtask dbt_debug
[2025-02-05T07:24:51.701+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_bash_dag_okok.dbt_debug manual__2025-02-05T07:24:48.222280+00:00 [running]> on host 06ae037e0797
[2025-02-05T07:24:51.945+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_bash_dag_okok' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T07:24:48.222280+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T07:24:48.222280+00:00'
[2025-02-05T07:24:51.949+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T07:24:51.989+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-05T07:24:51.991+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_projects/project_1 && dbt debug --profiles-dir /opt/***/dbt_projects/project_1']
[2025-02-05T07:24:52.018+0000] {subprocess.py:86} INFO - Output:
[2025-02-05T07:24:59.441+0000] {subprocess.py:93} INFO - [0m07:24:59  Running with dbt=1.8.8
[2025-02-05T07:24:59.546+0000] {subprocess.py:93} INFO - [0m07:24:59  dbt version: 1.8.8
[2025-02-05T07:24:59.554+0000] {subprocess.py:93} INFO - [0m07:24:59  python version: 3.12.4
[2025-02-05T07:24:59.561+0000] {subprocess.py:93} INFO - [0m07:24:59  python path: /home/***/.local/bin/python
[2025-02-05T07:24:59.568+0000] {subprocess.py:93} INFO - [0m07:24:59  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-02-05T07:25:04.058+0000] {subprocess.py:93} INFO - [0m07:25:04  Using profiles dir at /opt/***/dbt_projects/project_1
[2025-02-05T07:25:04.063+0000] {subprocess.py:93} INFO - [0m07:25:04  Using profiles.yml file at /opt/***/dbt_projects/project_1/profiles.yml
[2025-02-05T07:25:04.067+0000] {subprocess.py:93} INFO - [0m07:25:04  Using dbt_project.yml file at /opt/***/dbt_projects/project_1/dbt_project.yml
[2025-02-05T07:25:04.074+0000] {subprocess.py:93} INFO - [0m07:25:04  adapter type: snowflake
[2025-02-05T07:25:04.080+0000] {subprocess.py:93} INFO - [0m07:25:04  adapter version: 1.8.4
[2025-02-05T07:25:04.872+0000] {subprocess.py:93} INFO - [0m07:25:04  Configuration:
[2025-02-05T07:25:04.878+0000] {subprocess.py:93} INFO - [0m07:25:04    profiles.yml file [[32mOK found and valid[0m]
[2025-02-05T07:25:04.891+0000] {subprocess.py:93} INFO - [0m07:25:04    dbt_project.yml file [[32mOK found and valid[0m]
[2025-02-05T07:25:04.899+0000] {subprocess.py:93} INFO - [0m07:25:04  Required dependencies:
[2025-02-05T07:25:04.952+0000] {subprocess.py:93} INFO - [0m07:25:04   - git [[32mOK found[0m]
[2025-02-05T07:25:04.960+0000] {subprocess.py:93} INFO - 
[2025-02-05T07:25:04.962+0000] {subprocess.py:93} INFO - [0m07:25:04  Connection:
[2025-02-05T07:25:04.965+0000] {subprocess.py:93} INFO - [0m07:25:04    account: nmbqhvk-ns46391
[2025-02-05T07:25:04.974+0000] {subprocess.py:93} INFO - [0m07:25:04    user: TUAN_123
[2025-02-05T07:25:04.980+0000] {subprocess.py:93} INFO - [0m07:25:04    database: DBT_TEST
[2025-02-05T07:25:04.985+0000] {subprocess.py:93} INFO - [0m07:25:04    warehouse: MY_WAREHOUSE
[2025-02-05T07:25:04.991+0000] {subprocess.py:93} INFO - [0m07:25:04    role: MY_ROLE
[2025-02-05T07:25:04.995+0000] {subprocess.py:93} INFO - [0m07:25:04    schema: MAIN
[2025-02-05T07:25:05.001+0000] {subprocess.py:93} INFO - [0m07:25:05    authenticator: None
[2025-02-05T07:25:05.008+0000] {subprocess.py:93} INFO - [0m07:25:05    oauth_client_id: None
[2025-02-05T07:25:05.013+0000] {subprocess.py:93} INFO - [0m07:25:05    query_tag: None
[2025-02-05T07:25:05.018+0000] {subprocess.py:93} INFO - [0m07:25:05    client_session_keep_alive: False
[2025-02-05T07:25:05.026+0000] {subprocess.py:93} INFO - [0m07:25:05    host: None
[2025-02-05T07:25:05.032+0000] {subprocess.py:93} INFO - [0m07:25:05    port: None
[2025-02-05T07:25:05.039+0000] {subprocess.py:93} INFO - [0m07:25:05    proxy_host: None
[2025-02-05T07:25:05.044+0000] {subprocess.py:93} INFO - [0m07:25:05    proxy_port: None
[2025-02-05T07:25:05.049+0000] {subprocess.py:93} INFO - [0m07:25:05    protocol: None
[2025-02-05T07:25:05.054+0000] {subprocess.py:93} INFO - [0m07:25:05    connect_retries: 1
[2025-02-05T07:25:05.059+0000] {subprocess.py:93} INFO - [0m07:25:05    connect_timeout: None
[2025-02-05T07:25:05.062+0000] {subprocess.py:93} INFO - [0m07:25:05    retry_on_database_errors: False
[2025-02-05T07:25:05.066+0000] {subprocess.py:93} INFO - [0m07:25:05    retry_all: False
[2025-02-05T07:25:05.070+0000] {subprocess.py:93} INFO - [0m07:25:05    insecure_mode: False
[2025-02-05T07:25:05.075+0000] {subprocess.py:93} INFO - [0m07:25:05    reuse_connections: None
[2025-02-05T07:25:05.080+0000] {subprocess.py:93} INFO - [0m07:25:05  Registered adapter: snowflake=1.8.4
[2025-02-05T07:25:06.955+0000] {subprocess.py:93} INFO - [0m07:25:06    Connection test: [[32mOK connection ok[0m]
[2025-02-05T07:25:06.957+0000] {subprocess.py:93} INFO - 
[2025-02-05T07:25:06.959+0000] {subprocess.py:93} INFO - [0m07:25:06  [32mAll checks passed![0m
[2025-02-05T07:25:09.228+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-05T07:25:09.234+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T07:25:09.427+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_bash_dag_okok, task_id=dbt_debug, run_id=manual__2025-02-05T07:24:48.222280+00:00, execution_date=20250205T072448, start_date=20250205T072451, end_date=20250205T072509
[2025-02-05T07:25:09.563+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-02-05T07:25:09.674+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T07:25:09.683+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
