[2025-02-05T08:32:53.258+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-02-05T08:32:53.371+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: dbt_bash_dag_okok.dbt_debug manual__2025-02-05T08:32:42.220752+00:00 [queued]>
[2025-02-05T08:32:53.423+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: dbt_bash_dag_okok.dbt_debug manual__2025-02-05T08:32:42.220752+00:00 [queued]>
[2025-02-05T08:32:53.426+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2025-02-05T08:32:53.525+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): dbt_debug> on 2025-02-05 08:32:42.220752+00:00
[2025-02-05T08:32:53.558+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62: DeprecationWarning: This process (pid=2210) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-02-05T08:32:53.571+0000] {standard_task_runner.py:64} INFO - Started process 2211 to run task
[2025-02-05T08:32:53.572+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'dbt_bash_dag_okok', 'dbt_debug', 'manual__2025-02-05T08:32:42.220752+00:00', '--job-id', '46', '--raw', '--subdir', 'DAGS_FOLDER/test_dbt_2.py', '--cfg-path', '/tmp/tmp302rhxf5']
[2025-02-05T08:32:53.583+0000] {standard_task_runner.py:91} INFO - Job 46: Subtask dbt_debug
[2025-02-05T08:32:53.867+0000] {task_command.py:426} INFO - Running <TaskInstance: dbt_bash_dag_okok.dbt_debug manual__2025-02-05T08:32:42.220752+00:00 [running]> on host 06ae037e0797
[2025-02-05T08:32:54.476+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='dbt_bash_dag_okok' AIRFLOW_CTX_TASK_ID='dbt_debug' AIRFLOW_CTX_EXECUTION_DATE='2025-02-05T08:32:42.220752+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-05T08:32:42.220752+00:00'
[2025-02-05T08:32:54.486+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-02-05T08:32:54.602+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-05T08:32:54.608+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'cd /opt/***/dbt_projects/project_1 && dbt debug --profiles-dir /opt/***/dbt_projects/project_1']
[2025-02-05T08:32:54.658+0000] {subprocess.py:86} INFO - Output:
[2025-02-05T08:33:09.419+0000] {subprocess.py:93} INFO - [0m08:33:09  Running with dbt=1.8.8
[2025-02-05T08:33:09.473+0000] {subprocess.py:93} INFO - [0m08:33:09  dbt version: 1.8.8
[2025-02-05T08:33:09.477+0000] {subprocess.py:93} INFO - [0m08:33:09  python version: 3.12.4
[2025-02-05T08:33:09.480+0000] {subprocess.py:93} INFO - [0m08:33:09  python path: /home/***/.local/bin/python
[2025-02-05T08:33:09.484+0000] {subprocess.py:93} INFO - [0m08:33:09  os info: Linux-5.15.167.4-microsoft-standard-WSL2-x86_64-with-glibc2.36
[2025-02-05T08:33:14.870+0000] {subprocess.py:93} INFO - [0m08:33:14  Using profiles dir at /opt/***/dbt_projects/project_1
[2025-02-05T08:33:14.877+0000] {subprocess.py:93} INFO - [0m08:33:14  Using profiles.yml file at /opt/***/dbt_projects/project_1/profiles.yml
[2025-02-05T08:33:14.881+0000] {subprocess.py:93} INFO - [0m08:33:14  Using dbt_project.yml file at /opt/***/dbt_projects/project_1/dbt_project.yml
[2025-02-05T08:33:14.886+0000] {subprocess.py:93} INFO - [0m08:33:14  adapter type: snowflake
[2025-02-05T08:33:14.890+0000] {subprocess.py:93} INFO - [0m08:33:14  adapter version: 1.8.4
[2025-02-05T08:33:15.504+0000] {subprocess.py:93} INFO - [0m08:33:15  Configuration:
[2025-02-05T08:33:15.509+0000] {subprocess.py:93} INFO - [0m08:33:15    profiles.yml file [[32mOK found and valid[0m]
[2025-02-05T08:33:15.515+0000] {subprocess.py:93} INFO - [0m08:33:15    dbt_project.yml file [[32mOK found and valid[0m]
[2025-02-05T08:33:15.519+0000] {subprocess.py:93} INFO - [0m08:33:15  Required dependencies:
[2025-02-05T08:33:15.555+0000] {subprocess.py:93} INFO - [0m08:33:15   - git [[32mOK found[0m]
[2025-02-05T08:33:15.557+0000] {subprocess.py:93} INFO - 
[2025-02-05T08:33:15.561+0000] {subprocess.py:93} INFO - [0m08:33:15  Connection:
[2025-02-05T08:33:15.568+0000] {subprocess.py:93} INFO - [0m08:33:15    account: nmbqhvk-ns46391
[2025-02-05T08:33:15.573+0000] {subprocess.py:93} INFO - [0m08:33:15    user: TUAN_123
[2025-02-05T08:33:15.581+0000] {subprocess.py:93} INFO - [0m08:33:15    database: DBT_TEST
[2025-02-05T08:33:15.585+0000] {subprocess.py:93} INFO - [0m08:33:15    warehouse: MY_WAREHOUSE
[2025-02-05T08:33:15.590+0000] {subprocess.py:93} INFO - [0m08:33:15    role: MY_ROLE
[2025-02-05T08:33:15.599+0000] {subprocess.py:93} INFO - [0m08:33:15    schema: MAIN
[2025-02-05T08:33:15.606+0000] {subprocess.py:93} INFO - [0m08:33:15    authenticator: None
[2025-02-05T08:33:15.615+0000] {subprocess.py:93} INFO - [0m08:33:15    oauth_client_id: None
[2025-02-05T08:33:15.621+0000] {subprocess.py:93} INFO - [0m08:33:15    query_tag: None
[2025-02-05T08:33:15.627+0000] {subprocess.py:93} INFO - [0m08:33:15    client_session_keep_alive: False
[2025-02-05T08:33:15.632+0000] {subprocess.py:93} INFO - [0m08:33:15    host: None
[2025-02-05T08:33:15.637+0000] {subprocess.py:93} INFO - [0m08:33:15    port: None
[2025-02-05T08:33:15.645+0000] {subprocess.py:93} INFO - [0m08:33:15    proxy_host: None
[2025-02-05T08:33:15.651+0000] {subprocess.py:93} INFO - [0m08:33:15    proxy_port: None
[2025-02-05T08:33:15.655+0000] {subprocess.py:93} INFO - [0m08:33:15    protocol: None
[2025-02-05T08:33:15.661+0000] {subprocess.py:93} INFO - [0m08:33:15    connect_retries: 1
[2025-02-05T08:33:15.665+0000] {subprocess.py:93} INFO - [0m08:33:15    connect_timeout: None
[2025-02-05T08:33:15.670+0000] {subprocess.py:93} INFO - [0m08:33:15    retry_on_database_errors: False
[2025-02-05T08:33:15.674+0000] {subprocess.py:93} INFO - [0m08:33:15    retry_all: False
[2025-02-05T08:33:15.680+0000] {subprocess.py:93} INFO - [0m08:33:15    insecure_mode: False
[2025-02-05T08:33:15.684+0000] {subprocess.py:93} INFO - [0m08:33:15    reuse_connections: None
[2025-02-05T08:33:15.688+0000] {subprocess.py:93} INFO - [0m08:33:15  Registered adapter: snowflake=1.8.4
[2025-02-05T08:33:17.521+0000] {subprocess.py:93} INFO - [0m08:33:17    Connection test: [[32mOK connection ok[0m]
[2025-02-05T08:33:17.523+0000] {subprocess.py:93} INFO - 
[2025-02-05T08:33:17.527+0000] {subprocess.py:93} INFO - [0m08:33:17  [32mAll checks passed![0m
[2025-02-05T08:33:19.881+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-02-05T08:33:19.885+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-02-05T08:33:19.959+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=dbt_bash_dag_okok, task_id=dbt_debug, run_id=manual__2025-02-05T08:32:42.220752+00:00, execution_date=20250205T083242, start_date=20250205T083253, end_date=20250205T083319
[2025-02-05T08:33:20.088+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-02-05T08:33:20.137+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-05T08:33:20.143+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
